name: hexawave
description: "A Simple Music Player Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  file_picker: ^10.3.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  freezed_annotation: ^2.1.0
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.1.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

 